kind: api
apiVersion: api.webmethods.io/beta
metadata:
  name: PpastPetstoreAPI
  version: 1.0
  namespace: default
  tags:
    - swagger
    - petstore
    - sample
  type: REST
spec:
  api-spec:
    $path: "spec.yaml"
  policy-seq: 
    - $ref: default:Ppastpet_policies:1.0