kind: Route
apiVersion: api.webmethods.io/beta
metadata:
  name: "my-Straight-through-routing"
spec:
  endpoint:
    $ref: default_endpoint
---
kind: Route
apiVersion: api.webmethods.io/beta
metadata:
  name: "my-conditional-routing"
spec:
     - condition: |
        "(${request.headers.test} equals test1) or
        (${request.headers.test} notEquals ${request.payload.jsonPath[$.customer.name]})"
       endpoint:
          $ref: "endpoint_sample"
     - endpoint:
          $ref: "default_endpoint"
---
kind: Route
apiVersion: api.webmethods.io/beta
metadata:
  name: "my-load-balance-option2"
spec:
  loadbalance-endpoints:
    - $ref: default_endpoint
      suspend-on-duration: 40s
    - $ref: endpoint_sample
      suspend-on-duration: 40s

--- #combined
spec:
  loadbalance-endpoints:
    - $ref: default_endpoint
      suspend-on-duration: 40s
    - $ref: endpoint_sample
      suspend-on-duration: 40s

  endpoint:
    $ref: default_endpoint

  - condition: |
        "(${request.headers.test} equals test1) or
        (${request.headers.test} notEquals ${request.payload.jsonPath[$.customer.name]})"
    endpoint:
        $ref: "endpoint_sample"
  - endpoint:
        $ref: "default_endpoint"